#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Ensure Typescript files have no errors before pushing
# Ensure there is no linting or formatting errors before pushing
pnpm turbo run --parallel lint format typecheck